phongchongtoipham/Areas/Admin/Controllers/CrimeController.cs
using Microsoft.AspNetCore.Mvc;
using phongchongtoipham.Controllers;
using phongchongtoipham.Models;
using Microsoft.EntityFrameworkCore;


namespace phongchongtoipham.Areas.Admin.Controllers
{
     public class CrimeController : Controller
    {
        PctpdbContext db = new PctpdbContext();
        private readonly ILogger<HomeController> _logger;

        public CrimeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [HttpPost]
        public async Task<JsonResult> Add(int id, string name, string type,DateOnly date,string location, string status, IFormFile image)
        {
            var p = new CrimeList();
            if (image != null && image.Length > 0)
            {
                var fileName = Path.GetFileName(image.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "crimeImg", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    image.CopyTo(stream);
                }

                p.Image = fileName;
            }
            p.Id = id;
            p.Name = name;
            p.Type = type;
            p.Date = date;
            p.Location = location;
            p.Status = status;
            try
            {
                db.CrimeLists.Add(p);
                await db.SaveChangesAsync();
            }
            catch
            {
                return Json(new { Message = "ID tội phạm đã tồn tại" });
            }
            return Json(new { Message = "Thêm tội phạm thành công" });
        }
        [HttpPost]
        public async Task<JsonResult> Edit(int id, string name, string type, DateOnly date, string location, string status, IFormFile image)
        {
            var p = await db.CrimeLists.FindAsync(id);
            if (image != null && image.Length > 0)
            {
                var fileName = Path.GetFileName(image.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "crimeImg", fileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await image.CopyToAsync(stream);
                }
                if (!string.IsNullOrEmpty(p.Image))
                {
                    string oldImagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "crimeImg", p.Image);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                p.Image = fileName;
            }
            p.Name = name;
            p.Type = type;
            p.Date = date;
            p.Location = location;
            p.Status = status;

            await db.SaveChangesAsync();

            return Json(new { Message = "Sửa tội phạm thành công" });
        }
        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            var p = await db.CrimeLists.FindAsync(id);
            if (p.Image != null)
            {
                string imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "crimeImg", p.Image);

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }
            if (p != null)
            {
                db.CrimeLists.Remove(p);
            }
            await db.SaveChangesAsync();
            return RedirectToAction("CrimeManagement", "Admin", new { area = "Admin" });
        }
    }
}

phongchongtoipham/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using phongchongtoipham.Controllers;
using phongchongtoipham.Models;

namespace phongchongtoipham.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        PctpdbContext db = new PctpdbContext();
        private readonly ILogger<HomeController> _logger;

        public PostController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [HttpPost]
        public JsonResult PostRequest(string title, string c1, string c2, string c3, IFormFile image)
        {
            var p = new Blog();
            
            if (image != null && image.Length > 0)
            {
                var fileName = Path.GetFileName(image.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "blogImg", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    image.CopyTo(stream);
                }

                p.Image = fileName;
            }
            p.Title = title;
            p.Content1 = c1;
            p.Content2 = c2;
            p.Content3 = c3;
            db.Blogs.Add(p);
            db.SaveChanges();
            return Json(new { Message = "Thành công" });
        }
    }
}

phongchongtoipham/Areas/Admin/Views/Admin/CrimeManagement.cshtml
@{
    ViewData["Title"] = "CrimeManagement";
    Layout = "~/Areas/Admin/Views/Shared/_Layoutadmin.cshtml";
}

@model Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<phongchongtoipham.Models.CrimeList>

<main>
    <div class="qltk">
        <h2>Quản lý tội phạm</h2>
        <button id="AddFormButton" class="btn btn-primary">Thêm tội phạm</button>
        <div id="AddForm" class="formContent">
            <h2>Thêm tội phạm</h2>
            <div id="AddresultMessage"></div>
            <form id="AddformAJAX">
                <div>
                    <label>Id:</label>
                    <input id="addcrimeid" type="text" requi    red />
                </div>
                <div>
                    <label>Họ tên:</label>
                    <input id="addname" type="text" required />
                </div>
                <div>
                    <label>Tội danh:</label>
                    <input id="addtype" type="text" required />
                </div>
                <div>
                    <label>Ngày phạm tội:</label>
                    <input id="adddate" type="text" required />
                </div>
                <div>
                    <label>Địa điểm:</label>
                    <input id="addlocation" type="text" required />
                </div>
                <div>
                    <label>Trạng thái:</label>
                    <input id="addstatus" type="text" required />
                </div>
                <div>
                    <label>Hình ảnh:</label>
                    <input id="addimage" type="file" accept=".png" required />
                </div>

                <div class="btn-group">
                    <button id="submitAddform" type="button" class="btn btn-first">Thêm</button>
                    <button id="CloseAddForm" type="button" class="btn btn-second">Đóng</button>
                </div>
            </form>
        </div>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Date</th>
                    <th>Location</th>
                    <th>Status</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>@item.Type</td>
                        <td>@item.Date</td>
                        <td>@item.Location</td>
                        <td>@item.Status</td>
                        <td><img src="@Url.Content("../crimeImg/" + item.Image)" alt="hình ảnh chỉ mang tính chất mình họa" width="80"></td>
                        <td>
                            <p class="EditFormButton">Sửa</p>
                            <div class="EditForm formContent">
                                <h2>Sửa thông tin</h2>
                                <div class="EditresultMessage"></div>
                                <form>
                                    <label for="name">Họ tên:</label>
                                    <input type="text" class="name" value="@item.Name" required>

                                    <label for="type">Tội danh:</label>
                                    <input type="text" class="type" value="@item.Type" required>

                                    <label for="date">Ngày phạm tội:</label>
                                    <input type="text" class="date" value="@item.Date" required>

                                    <label for="location">Địa điểm:</label>
                                    <input type="text" class="location" value="@item.Location" required>

                                    <label for="status">Trạng thái:</label>
                                    <input class="status" type="text" value="@item.Status" required />

                                    <label>Ảnh:</label>
                                    <input accept=".png" type="file" class="editimage" />
                                    <img src="@Url.Content("../crimeImg/" + item.Image)" alt="Ảnh sản phẩm" width="100" />

                                    <input type="text" value="@item.Id" class="editid" style="display: none;" />
                                    <div class="btn-group">
                                        <button type="button" class="submitEditform btn btn-first">Lưu</button>
                                        <button type="button" class="CloseEditForm btn btn-second">Đóng</button>
                                    </div>
                                </form>
                            </div>
                        </td>
                        <td>
                            <form action="~/Crime/Remove" method="post" style="display: inline;">
                                <button type="submit" name="id" value="@item.Id" class="btn btn-danger">Xóa</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</main>
<script src="~/lib/jquery/jquery.min.js"></script>
<script>
            <!--đóng form, sửa form-- >
        document.querySelectorAll(".EditFormButton").forEach(function (button) {
            button.addEventListener("click", function () {
                var editForm = this.nextElementSibling;
                editForm.style.display = "block";
                document.getElementById("overlay").style.display = "block";
            });
        });

    document.querySelectorAll(".CloseEditForm").forEach(function (button) {
        button.addEventListener("click", function () {
            var editForm = this.closest(".EditForm");
            editForm.style.display = "none";
            document.getElementById("overlay").style.display = "none";
        });
    });

    document.getElementById("AddFormButton").addEventListener("click", function () {
        document.getElementById("AddForm").style.display = "block";
        document.getElementById("overlay").style.display = "block";
    });

    document.getElementById("CloseAddForm").addEventListener("click", function () {
        document.getElementById("AddForm").style.display = "none";
        document.getElementById("overlay").style.display = "none";
    });

</script>
<script>
    $(document).ready(function () {
        $('#submitAddform').click(function () {
            var tid = $('#addcrimeid').val();
            var tname = $('#addname').val();
            var ttype = $('#addtype').val();
            var tdate = $('#adddate').val();
            var tlocation = $('#addlocation').val();
            var tstatus = $('#addstatus').val();
            var timage = $('#addimage').val();
           
            var formData = new FormData();
            formData.append('id', tid);
            formData.append('name', tname);
            formData.append('type', ttype);
            formData.append('date', tdate);
            formData.append('location', tlocation);
            formData.append('status', tstatus);
            formData.append('image', $('#addimage')[0].files[0]);
           

            $.ajax({
                url: '@Url.Action("Add", "Crime", new { area = "Admin" })',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data.message);
                    $('#AddresultMessage').text(data.message);
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('.submitEditform').click(function () {
            var formData = new FormData();
            formData.append('id', $('.editid').val());
            formData.append('name', $('.name').val());
            formData.append('type', $('.type').val());
            formData.append('date', $('.date').val());
            formData.append('location', $('.location').val());
            formData.append('status', $('.status').val());
            formData.append('image', $('.editimage')[0].files[0]);
       

            $.ajax({
                url: '@Url.Action("Edit", "Crime", new { area = "Admin" })',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data.message);
                    $('.EditresultMessage').text(data.message);
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });
</script>

phongchongtoipham/Areas/Admin/Views/Admin/PostManagement.cshtml
@{
    ViewData["Title"] = "PostManagement";
    Layout = "~/Areas/Admin/Views/Shared/_Layoutadmin.cshtml";
}

<script type="text/javascript" src="~/js/froala_editor.pkgd.min.js"></script>
<link href="~/cssLayout/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />




<div class="mainFrame">

    <div class="mainPost">
        <div id="EditresultMessage"></div>
        <form class="formButton" id="formBlog">

            <div class="form-group">
                <label>Tiêu đề:</label>
                <input type="text" class="form-control" id="title" required />
            </div>

            <div class="form-group">
                <label>Ảnh đại diện:</label>
                <input accept=".png" type="file" id="avatar" required />
            </div>


            <textarea asp-for=Content id="c1"></textarea>
            <textarea asp-for=Content id="c2"></textarea>
            <textarea asp-for=Content id="c3"></textarea>
            <button type="button" id="post">Submit</button>
        </form>

        <script>
            var editor = new FroalaEditor('#c1', {
                toolbarButtons: [['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript'], ['fontFamily', 'fontSize', 'textColor', 'backgroundColor'], ['inlineClass', 'inlineStyle', 'clearFormatting']]
            });
            var editor = new FroalaEditor('#c2', {
                toolbarButtons: [['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript'], ['fontFamily', 'fontSize', 'textColor', 'backgroundColor'], ['inlineClass', 'inlineStyle', 'clearFormatting']]
            });
            var editor = new FroalaEditor('#c3', {
                toolbarButtons: [['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript'], ['fontFamily', 'fontSize', 'textColor', 'backgroundColor'], ['inlineClass', 'inlineStyle', 'clearFormatting']]
            });
        </script>
    </div>
</div>
<script src="~/lib/jquery/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        $('#post').click(function () {
            var formData = new FormData();
            formData.append('title', $('#title').val());
            formData.append('c1', $('#c1').val());
            formData.append('c2', $('#c2').val());
            formData.append('c3', $('#c3').val());
            formData.append('image', $('#avatar')[0].files[0]);



            $.ajax({
                url: '@Url.Action("PostRequest", "Post", new { area = "Admin" })',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data.message);
                    $('#EditresultMessage').text(data.message);
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });
</script>

<style>
    .mainFrame {
        width: 80%;
        margin: 0 auto;
        padding: 20px;
        background-color: #f7f7f7;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-top: 10px
    }
</style>

phongchongtoipham/Areas/Admin/Views/Admin/ReportManagement.cshtml
@{
    ViewData["Title"] = "ReportManagement";
    Layout = "~/Areas/Admin/Views/Shared/_Layoutadmin.cshtml";
}
@model Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<phongchongtoipham.Models.Report>
<main>
    <div class="qltk">
        <h2>Quản lý báo cáo</h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Date</th>
                    <th>location</th>
                    <th>Detail</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Type</td>
                    <td>@item.Date</td>
                    <td>@item.Location</td>
                    <td>@item.Detail</td>
                    <td><img src="@Url.Content("../crimeImg/" + item.Image)" alt="hình ảnh báo cáo tội phạm" width="80px"></td>
                    <td>
                        <form action="~/Report/Accept" method="post" style="display: inline;">
                            <button type="submit" name="id" value="@item.Id" class="AcceptButton">Accept</button>
                        </form>
                    </td>
                    <td>
                        <form action="~/Report/Accept" method="post" style="display: inline;">
                            <button type="submit" name="id" value="@item.Id" class="RejectButton">Reject</button>
                        </form>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>

</main>
<script src="~/lib/jquery/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('.AcceptButton').click(function () {
            var tid = $('.rpid').val();
            var tfullname = $('.fullname').val();
            var temail = $('.email').val();
            var tphone = $('.phone').val();
            var tpass1 = $('.password').val();
            var trole = $('.role').val();


            $.ajax({
                url: '@Url.Action("Add", "Crime", new { area = "Admin" })',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data.message);
                    $('#AddresultMessage').text(data.message);
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });
</script>

phongchongtoipham/Areas/Admin/Views/Admin/UserManagement.cshtml
@{
    ViewData["Title"] = "UserManagement";
    Layout = "~/Areas/Admin/Views/Shared/_Layoutadmin.cshtml";
}

@model Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<phongchongtoipham.Models.User>


<main>
    <div class="qltk">
        <h2 class="title">Quản lý tài khoản</h2>
        <button id="AddFormButton" class="btn btn-primary">Thêm tài khoản</button>
        <div id="AddForm" class="formContent">
            <h2>Thêm tài khoản</h2>
            <div id="AddresultMessage"></div>
            <form id="AddformAJAX">
                <div>
                    <label>Tên tài khoản:</label>
                    <input id="UserAddName" type="text" required />
                </div>
                <div>
                    <label>Họ tên:</label>
                    <input id="UserAddFullName" type="text" required />
                </div>
                <div>
                    <label>Email:</label>
                    <input id="UserAddEmail" type="text" required />
                </div>
                <div>
                    <label>Số điện thoại:</label>
                    <input id="UserAddPhone" type="text" required />
                </div>
                <div>
                    <label>Mật khẩu:</label>
                    <input id="UserAddPass1" type="text" required />
                </div>
                <div>
                    <label>Lặp lại mật khẩu:</label>
                    <input id="UserAddPass2" type="text" required />
                </div>
                <div>
                    <label>Vai trò:</label>
                    <input id="UserAddRole" type="text" required />
                </div>

                <div class="btn-group">
                    <button id="submitAddform" type="button" class="btn btn-first">Thêm</button>
                    <button id="CloseAddForm" type="button" class="btn btn-second">Đóng</button>
                </div>
            </form>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Fullname</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Password</th>
                    <th>Role</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>@item.UserName</td>
                        <td>@item.FullName</td>
                        <td>@item.Email</td>
                        <td>@item.Phone</td>
                        <td>@item.Password</td>
                        @if (item.Role == 99)
                        {
                            <td>Admin</td>
                        }
                        else
                        {
                            <td>User</td>
                        }
                        <td>
                            <p class="EditFormButton">Sửa</p>
                            <div class="EditForm formContent">
                                <h2>Sửa tài khoản</h2>
                                <div id="resulteditMessage"></div>
                                <form>
                                    
                                    <label for="fullname">Họ tên:</label>
                                    <input type="text" class="fullname" value="@item.FullName" required>

                                    <label for="password">Mật khẩu:</label>
                                    <input type="text" class="password" value="@item.Password" required>

                                    <label for="email">Email:</label>
                                    <input type="text" class="email" value="@item.Email" required>

                                    <label for="phone">Số điện thoại:</label>
                                    <input type="text" class="phone" value="@item.Phone" required>
                                    
                                    <label for="role">Vai trò:</label>
                                    @if (item.Role == 99)
                                    {
                                        <input type="text" class="role" value="Admin" required>
                                    }
                                    else
                                    {
                                        <input type="text" class="role" value="User" required>
                                    }
                                    <input type="text" value="@item.UserName" class="editusername" style="display: none;" />

                                    <div class="btn-group">
                                        <button type="button" class="submitEditform btn btn-first">Lưu</button>
                                        <button type="button" class="CloseEditForm btn btn-second">Đóng</button>
                                    </div>
                                </form>
                            </td>
                        <td>
                            <form action="~/User/Remove" method="post" style="display: inline;">
                                <button type="submit" name="username" value="@item.UserName" class="btn btn-danger">Xóa</button>
                            </form>
                         </td>

                    </tr>                
                }
            </tbody>
        </table>
    </div>



</main>


<script src="~/lib/jquery/jquery.min.js"></script>
<script>
        <!--đóng form, sửa form-- >
        document.querySelectorAll(".EditFormButton").forEach(function (button) {
            button.addEventListener("click", function () {
                var editForm = this.nextElementSibling;
                editForm.style.display = "block";
                document.getElementById("overlay").style.display = "block";
            });
        });

    document.querySelectorAll(".CloseEditForm").forEach(function (button) {
        button.addEventListener("click", function () {
            var editForm = this.closest(".EditForm");
            editForm.style.display = "none";
            document.getElementById("overlay").style.display = "none";
        });
    });

    document.getElementById("AddFormButton").addEventListener("click", function () {
        document.getElementById("AddForm").style.display = "block";
        document.getElementById("overlay").style.display = "block";
    });

    document.getElementById("CloseAddForm").addEventListener("click", function () {
        document.getElementById("AddForm").style.display = "none";
        document.getElementById("overlay").style.display = "none";
    });

</script>
<script>
    $(document).ready(function () {
        $('#submitAddform').click(function () {
            var tusername = $('#UserAddName').val();
            var tfullname = $('#UserAddFullName').val();
            var temail = $('#UserAddEmail').val();
            var tphone = $('#UserAddPhone').val();
            var tpass1 = $('#UserAddPass1').val();
            var tpass2 = $('#UserAddPass2').val();
            var trole = $('#UserAddRole').val();

            $.ajax({
                url: '@Url.Action("Add", "User", new { area = "Admin" })',
                type: 'POST',
                data: { username: tusername, fullname: tfullname, email: temail, phone:tphone, password1: tpass1, password2: tpass2, role: trole },
                success: function (data) {
                    console.log(data.message);
                    $('#AddresultMessage').text(data.message);
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('.submitEditform').click(function () {
            var tusername = $('.editusername').val();
            var tfullname = $('.fullname').val();
            var temail = $('.email').val();
            var tphone = $('.phone').val();
            var tpass1 = $('.password').val();
            var trole = $('.role').val();

            $.ajax({
                url: '@Url.Action("Edit", "User", new { area = "Admin" })',
                type: 'POST',
                data: { username: tusername, fullname: tfullname, email: temail, phone: tphone, password: tpass1, role: trole },
                success: function (data) {
                    console.log(data.message);
                    $('#resulteditMessage').text(data.message);
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });
</script>